version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:
  cassandra:
    image: cassandra
    ports:
    - 7000
    volumes:
    - cassandradata:/var/lib/cassandra
    
  redis:
    image: redis
    ports:
      - "6379:6379"
      
  mongodb: 
    image: mongo 
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest
#   command: --smallfiles --rest --auth  

volumes:
  mongodata:  
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data  
  cassandradata: 
        